### ISSUE TITLE
Copy does not work on attached model

### ISSUE THREAD

**Issue by fijal** [lightscapevr/vr-sketch-4#1]
To reproduce: select everything and try to copy

**Comment by fijal** [comment]
[volume.zip](https://github.com/lightscapevr/vr-sketch-4/files/1584921/volume.zip)

**Comment by arigo** [comment]
Ah, you can't copy if you're moving the selection holding a vertex.  Fixed in https://github.com/lightscapevr/vr-sketch-4/commit/b9b4e3415aac9c054c3b8bdee967bfe73b79913c
