### ISSUE TITLE
Wrong thing removed

### ISSUE THREAD

**Issue by fijal** [lightscapevr/vr-sketch-4#10]
When you remove the line that crosses the face in the middle, one of the faces is removed instead of line (a random one I think)

[volume2.zip](https://github.com/lightscapevr/vr-sketch-4/files/1596066/volume2.zip)

**Comment by arigo** [comment]
https://github.com/lightscapevr/vr-sketch-4/commit/4c3e75e1b94fb7e78aafa882eeca8fc92f6c7a07 might have fixed the original problem, which is that wrong geometry was created in the first place (duplicate edge).

**Comment by fijal** [comment]
Closing as it seems to be fixed
