### ISSUE TITLE
VR sketch crashes when closing

### ISSUE THREAD

**Issue by fijal** [lightscapevr/vr-sketch-4#18]
When using a build, pressing the red cross makes it crash. This is not a very good customer experience :-) we should also probably have a button to close on the windows too (at least in the build version)

**Comment by arigo** [comment]
A button... you probably mean somewhere else than on the 3D window, as there is already the red cross there?

**Comment by fijal** [comment]
Yes, somewhere else. Unclear if closing VR should save the sketchup file or you need to save it in sketchup anyway. Either way, the red X should not crash (even if we decide it's not worth adding another button)

**Comment by arigo** [comment]
Fixed by a hack in acefdf4.  If we find the reason for the hang in the first place, we might fix it more cleanly.  For now I'm checking this one in because the hang seems to be at a place with no C# code running.
