### ISSUE TITLE
Straight up teleport requires controller to be pointed very straight

### ISSUE THREAD

**Issue by fijal** [lightscapevr/vr-sketch-4#21]
I've seen people struggle to teleport "up", since they were not aiming their controller directly above. Maybe an opening "portal" that you have to aim at would help as they look up?

**Comment by arigo** [comment]
Note that "up" here means actually "up and a bit backwards".  This is done so that it's possible to teleport up a wall where you need to point the controller almost up, but always a tiny bit forward.  Changed the wording of the tooltip.

**Comment by arigo** [comment]
Closed for now.  I think Issue #29 might have a different answer for this when it is implemented.
