### ISSUE TITLE
Disable or hide section plane

### ISSUE THREAD

**Issue by fijal** [lightscapevr/vr-sketch-4#31]
Section plane right now has the tendency to greatly confuse newcomers. It should either be hidden behind some other tool or not enabled by default or be easier to remove (eg clicking when we have one section plane on the same section plane should do SOMETHING like rotate or remove, not create new one)

**Comment by arigo** [comment]
I'm thinking about this:

1. hide it behind Select;

2. when there is a section plane, the icon in the menu is replaced with a "remove the section plane" command.
