### ISSUE TITLE
Texture upload takes a very long time on massive models

### ISSUE THREAD

**Issue by fijal** [lightscapevr/vr-sketch-4#33]
I think we should strive for loading of models take roughly the same amount of time as loading the model in sketchup does. In very large models loading textures take more time than loading the model itself, sometimes significantly so.

Additionally there is very little feedback other than "model loading" and sketchup freezing, so it's impossible to decide whether it'll ever finish.

Another possibility is to implement caching, even locally, so the textures are cached between runs.

**Comment by arigo** [comment]
Added feedback and reduced a lot the time it takes in SketchUp to save the textures to files---turns out writing .jpg is an order of magnitude faster than writing .png, with SketchUp.
