### ISSUE TITLE
Experiment with delay on clicks

### ISSUE THREAD

**Issue by fijal** [lightscapevr/vr-sketch-4#5]
Another annoying feature - I hover over the right vertex until it's fixed, then press the button. But the vertex managed to snatch to something else in the meantime, creating bad line. Maybe if the switch of snatching happened in the last 50ms,we do use the previous one?

**Comment by arigo** [comment]
I seem to get good results with this: when the controller snaps to a point, the next frame, we tweak the controller position towards that point by some factor (~0.5 seems good).  This gives a far more stable impression when there are a lot of vertices in a small area, and I can still select the vertex I want naturally: if I want to pick the next point to the left I move the controller slowly to the left until the selection switches.  As soon as it does I tend naturally to go back a little bit; now doing so won't immediately jump back to the previous point.
